# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rsock.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brsock.proto\x12\x05rsock\"U\n\x10HandshakeRequest\x12\x0b\n\x03jwt\x18\x01 \x01(\t\x12\x13\n\x0binstanceKey\x18\x02 \x01(\t\x12\x11\n\tlaunchURL\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\t\"\"\n\x11HandshakeResponse\x12\r\n\x05token\x18\x01 \x01(\t\")\n\nDataPacket\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x32}\n\x07RSocket\x12>\n\tHandshake\x12\x17.rsock.HandshakeRequest\x1a\x18.rsock.HandshakeResponse\x12\x32\n\x06Tunnel\x12\x11.rsock.DataPacket\x1a\x11.rsock.DataPacket(\x01\x30\x01\x42\x44ZBgithub.com/NimbleBoxAI/nimblebox-rsock-server/v1/rsock_pb;rsock_pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rsock_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZBgithub.com/NimbleBoxAI/nimblebox-rsock-server/v1/rsock_pb;rsock_pb'
  _HANDSHAKEREQUEST._serialized_start=22
  _HANDSHAKEREQUEST._serialized_end=107
  _HANDSHAKERESPONSE._serialized_start=109
  _HANDSHAKERESPONSE._serialized_end=143
  _DATAPACKET._serialized_start=145
  _DATAPACKET._serialized_end=186
  _RSOCKET._serialized_start=188
  _RSOCKET._serialized_end=313
# @@protoc_insertion_point(module_scope)
